### ISSUE TITLE
How to run code on multiple machines？

### ISSUE THREAD

**Issue by ywdong** [LayneH/GreenMIM#7]
Wonderful job!  I wonder how can I run the code in  multiple machines?

**Comment by LayneH** [comment]
Hi,

If you are using Slurm, you can just specify [the number of GPUs](https://github.com/LayneH/GreenMIM/blob/main/scripts/srun_mae_swin_base.sh#L15) used for training at the command line, the code worked fine in our experiments.
Otherwise, please refer to [this link](https://lambdalabs.com/blog/multi-node-pytorch-distributed-training-guide/#write-multi-node-pytorch-distributed-applications) or other tutorials for instructions.
