### ISSUE TITLE
what does "ratio" mean in PatchMerging?

### ISSUE THREAD

**Issue by hollow-503** [LayneH/GreenMIM#9]
Thanks to your impressive work! However i met some problem.
In the `models_swin.py`, line 244:

```
ratio = H // 7 if H % 7 == 0 else H // 6   # FIXME
x = x.view(B, -1, ratio//2, 2, ratio//2, 2, C)
x = x.permute(0, 1, 2, 4, 3, 5, 6).reshape(B, L//4, 4 * C)
```

why you view `x` into `(B, -1, ratio//2, 2, ratio//2, 2, C)` and then reshape back to `(B, L//4, 4 * C)` ? Why not reshape `x` to `(B, H//2, 2, W//2, 2, C)`, and then reshape it to  `(B, L//4, 4 * C)` ? 
I found it when i change the image resolution, and don't know why.

**Comment by LayneH** [comment]
Hi, sorry for the late reply.

We can't reshape `x` to `(B, H//2, 2, W//2, 2, C)` since `L != H * W` (because we discarded the masked patches).

Here `ratio` is the ratio of the resolution at the current stage to that of the final stage. Since we have grouped the tokens into local windows of size `ratio * ratio` [here](https://github.com/LayneH/GreenMIM/blob/main/models_swin.py#L740), `x` is actually of shape `(B, N_final * ratio * ratio, C)`, where `N_final` is the number of visible tokens at the final stage. With this, we can merge the patches view-and-reshape.

**Comment by hollow-503** [comment]
> Hi, sorry for the late reply.
> 
> We can reshape `x` to `(B, H//2, 2, W//2, 2, C)` since `L != H * W` (because we discarded the masked patches).
> 
> Here `ratio` is the ratio of the resolution at the current stage to that of the final stage. Since we have grouped the tokens into local windows of size `ratio * ratio` [here](https://github.com/LayneH/GreenMIM/blob/main/models_swin.py#L740), `x` is actually of shape `(B, N_final * ratio * ratio, C)`, where `N_final` is the number of visible tokens at the final stage. With this, we can merge the patches view-and-reshape.

Thanks for your reply! Actually i usually crop the image to `256*704` and then send it to swin transformer. In the official repo, it doesn't require the resolution to be a multiple of `window_size`. Is there any hidden trouble if i reshape `x` to `(B, H//2, 2, W//2, 2, C)` straightly？

**Comment by LayneH** [comment]
I had a typo in the previous reply that we *can't* do that since `L != H * W`.
Even if you can reshape it in that way, it will only merge patches that are not from the same 2x2 windows.

In fact, the `ratio` is only dependent on the stage index of the current feature, independent of the input resolution, e.g., `ratio = 32 / 4 = 8` for the first stage (stride = 4). So one straightforward way to adapt to images of size other than 224x224 is directly passing the stage index or feature stride to calculate the `ratio` in`PatchMerge` module.

**Comment by LayneH** [comment]
Hi,

I pushed new commits to the main branch, refactoring the structure of this code base with some performance improvements.
As a result, you may not need to modify the code to train with different resolutions.

Please check out the new version.

**Comment by LayneH** [comment]
Close due to inactivity.
Feel free to reopen this issue if you have any further problems.
